#! /bin/sh
################





# Relative paths are search either in the parent of this configuration file
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap          9
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
nitrogen --restore &
polybar &
# Relative paths are search either in the parent of this configuration file
xrandr --output DVI-I-1 --mode 1920x1080 --rate 74 
setxkbmap -option grp:alt_shift_toggle us,ru &
picom &

